In [6]:
import numpy as np 
#arr=np.array([31,43,33,32,323])
#x=([true,fals,true,fals,true])
#newarr=arr[x]
print(arr)


[ 31  43  33  32 323]


In [9]:
#arr=np.array([3,4,34,34,33])
arr=np.array(['mango','goava','papaya','apple','graps'])
print(np.sort(arr))

['apple' 'goava' 'graps' 'mango' 'papaya']


In [24]:
arr1=np.array([324,42,245,4534,3,534])
                 
arr2=np.array([343,6,34,36,375,34,22])
#for x in arr1;
#print(x)
arr=np.concatenate([arr1,arr2])
print(np.sort(arr))

#arr[1]=12
print(arr1[0:1])
print(type(arr))
#print(arr,dtype)
print(arr)

[   3    6   22   34   34   36   42  245  324  343  375  534 4534]
[324]
<class 'numpy.ndarray'>
[ 324   42  245 4534    3  534  343    6   34   36  375   34   22]
